version: "3"
services:
  onboarding-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - shared-network
    volumes:
      - .:/code
      - python-packages:/usr/local/lib/python3.10/site-packages
      - python-bin:/usr/local/bin
    command: /bin/bash pytest

  db:
    image: postgres:latest
    volumes:
      - test-db-volme:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - shared-network
    environment:
      - POSTGRES_DB=onboarding_app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

networks:
  shared-network:
    driver: bridge

volumes:
  test-db-volme:
  python-packages:
  python-bin:
