[tool.poetry]
name = "portfolio-toy-project-mjkim"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.83.0"
email-validator = "^1.2.1"
uvicorn = "^0.18.3"
python-multipart = "^0.0.5"
SQLAlchemy = "^1.4.41"
python-jose = "^3.3.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
pytest = "^7.1.3"
requests = "^2.28.1"
alembic = "^1.8.1"
psycopg2-binary = "^2.9.5"



[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
