
name: Onboarding Project

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make dotenv
      run: |
        touch .env
        echo SECRET_KEY=SECRET_KEY >> .env
        echo POSTGRES_URL=postgresql://user:password@db:5432/onboarding_app >> .env
    - name: Test with pytest
      run: |
        docker compose -f docker-compose.test.yml run --rm onboarding-app /bin/bash -c "pytest"
        docker compose -f docker-compose.test.yml down
